### ISSUE TITLE
GitHub Pages failed

### ISSUE THREAD

**Issue by likundec** [mmistakes/made-mistakes-gatsby#358]
Hello, mmistakes,
I like your design style and your sites are really so cool!
However, when I try to fork to my GitHub, it seems like a compile error in GitHub Pages. The error information is :
The tag youtube on line 8 in line 50): Expected end_of_string but found colon in "{{SUP:data-footnote-backlink-ref}}" in /notes/autumn-refresh/ Liquid Exception: Liquid syntax error ( is not a recognized Liquid tag.

Is this a bug or something else?

:) Much thanks.
Kwin

**Comment by mmistakes** [comment]
This repo isn't a Jekyll site nor is it compatible with GitHub Pages.
Those Liquid errors look related to [my old Jekyll based site](https://github.com/mmistakes/made-mistakes-jekyll)... which uses custom plugins... which are also not supported with GitHub Pages.

You'll need to build it with a CI/CD solution like Netlify, Travis CI, etc. or use [GitHub actions](https://github.com/features/actions) to build then deploy to GitHub Pages.

**Comment by Max-ChenFei** [comment]
You can use github action to build and deploy on GitHub Page
```
      - uses: actions/checkout@v1
      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
            envkey_GITHUB_LOGIN: Max-ChenFei
            envkey_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.SECRET_KEY }}
            directory: <directory_name>
            file_name: .env
        
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.BLOG }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
```
